apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard-home.fullname" . }}-dns
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
  {{- with .Values.service.dns.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.dns.type }}
  externalTrafficPolicy: {{ .Values.service.dns.externalTrafficPolicy }}
  ports:
    - port: {{ .Values.service.dns.port }}
      targetPort: dns
      protocol: UDP
      name: dns
  selector:
    {{- include "adguard-home.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard-home.fullname" . }}-http
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.http.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpinit.port }}
      targetPort: 3000
      protocol: TCP
      name: http-init
  selector:
    {{- include "adguard-home.selectorLabels" . | nindent 4 }}