image:
  repository: adguard/adguardhome
  tag: latest
  pullPolicy: IfNotPresent

service:
  dns:
    type: ClusterIP
    port: 53
    externalTrafficPolicy: Cluster
  httpinit:
    type: ClusterIP
    port: 3000
  http:
    type: ClusterIP
    port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  # - host: adguard.cluster.local
  #   paths:
  #     - path: /
  #       pathType: Prefix
  tls: []
  #  - secretName: adguard-http-tls
  #    hosts:
  #      - adguard.cluster.local

persistence:
  enabled: false
  size: 1Gi
